### ISSUE TITLE
Did you use a script to generate your dev-nodejs?

### ISSUE THREAD

**Issue by orsonteodoro** [Jannis234/jm-overlay#11]
If you did, you have the script?

If not, would you be interested in being added as collaborator for https://github.com/orsonteodoro/pjson2ebuild ?

**Comment by Jannis234** [comment]
I didn't use a script, just a bunch of copy-and-pasting. I don't think that using a script would save me a lot of time since most ebuilds will need manual editing anyway (especially when implementing src_test).
