### ISSUE TITLE
Citra, does not compile even with the system-boost flag disabled.

### ISSUE THREAD

**Issue by aTosser** [Jannis234/jm-overlay#17]
>> Preparing source in /tmp/portage/games-emulation/citra-9999/work/citra-9999 ...
 * Applying citra-system-boost.patch ...
1 out of 2 hunks FAILED -- saving rejects to file CMakeLists.txt.rej
 [ !! ]
 * ERROR: games-emulation/citra-9999::jm-overlay failed (prepare phase):

**Comment by Jannis234** [comment]
Should be fixed now
