### ISSUE TITLE
Syncthingtray 1.2.1

### ISSUE THREAD

**Issue by 31JSON** [Jannis234/jm-overlay#24]
The current release version of syncthingtray is 1.2.1. Is it possible to get the overlay version updated? Version 1.1.17 is no longer compiling properly.

```
CMake Error at plasmoid/lib/CMakeLists.txt:15 (find_package):
  By not providing "Findqtquickforkawesome.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "qtquickforkawesome", but CMake did not find one.
  ```

**Comment by Jannis234** [comment]
Done, 1.2.1 is now in the overlay.

I remember encountering that specific error once but not being able to reproduce it afterwards. If it still occurs with 1.2.1, maybe try unmerging and reinstalling `dev-libs/qtforkawesome` and Syncthingtray to see if that fixes it.
