### ISSUE TITLE
Failing to emerge app-pda/sachesi-2.0.4::jm-overlay lrelease: No such file or directory

### ISSUE THREAD

**Issue by F3llFr0mTh3Sky** [Jannis234/jm-overlay#29]
Hello,
My gentoo system is up to date, latest portage and latest Qt 5.15.10-r1.
So the issue is app-pda/sachesi-2.0.4 fails to emerge.
See the logs here : http://0x0.st/HLly.txt http://0x0.st/HLlt.log
Some users on IRC pointed out that it might be related to this :
https://www.gentoo.org/support/news-items/2022-03-30-qt-5_15_3-bump.html

I found a similar issue here :
https://github.com/xsacha/Sachesi/issues/105

**Comment by F3llFr0mTh3Sky** [comment]
Bugfix :
Add this code before src_configure()
```
src_prepare() {
        default

        sed -i -e 's/lquazip/lquazip1-qt5/' Sachesi.pro || die

        "$(qt5_get_bindir)"/lrelease Sachesi.pro || die
}
```

**Comment by Jannis234** [comment]
Updated, thanks for providing the fix!

**Comment by F3llFr0mTh3Sky** [comment]
you welcome
