### ISSUE TITLE
libpsl-0.17.0-r1.ebuild (patch for libpsl-0.17.0)

### ISSUE THREAD

**Issue by t-dr** [Jannis234/jm-overlay#6]
Patch provides ability to build with multiple versions of python and has been tested with both python-3.4 and python-3.5.  

Previous error was:
"TypeError: unsupported operand type(s) for %: 'bytes' and 'float'"

7c7,9
< inherit multilib-minimal
---
> PYTHON_COMPAT=( python2_7 )
>
> inherit python-any-r1 multilib-minimal
30c32
< DEPEND="${RDEPEND}
---
> DEPEND="${RDEPEND} ${PYTHON_DEPS}

**Comment by Jannis234** [comment]
Thanks for pointing this out, should be fixed now

**Comment by t-dr** [comment]
Other versions could likely use the same patch.

Ted
