### ISSUE TITLE
games-arcade/stepmania-5.0.12 build failure

### ISSUE THREAD

**Issue by crocket** [Jannis234/jm-overlay#8]
```shell
$ emerge -pqv stepmania::jm-overlay
[ebuild  N    ] games-arcade/stepmania-5.0.12  USE="alsa default-songs ffmpeg gtk jpeg mp3 networking ogg -crash-handler -doc -gles2 -jack -oss -parport -pulseaudio -wav" CPU_FLAGS_X86="sse2" 
```

[build.log](https://github.com/Jannis234/jm-overlay/files/1346959/build.log)

**Comment by crocket** [comment]
The issue seems to be caused by ffmpeg 3.
https://github.com/stepmania/stepmania/issues/1364

**Comment by Jannis234** [comment]
Fixed, but I left in a system-ffmpeg USE flag that forces FFmpeg 2.
