### ISSUE TITLE
Unavailable repository 'dotnet' referenced by masters entry in '/var/lib/layman/jm-overlay/metadata/layout.conf'

### ISSUE THREAD

**Issue by crocket** [Jannis234/jm-overlay#9]
This warning keeps appearing whenever I use emerge or equery.
Because it appears repetitively, it is irritating.

**Comment by Jannis234** [comment]
This happens because of a missing repository that is referenced by my overlay. See issue #1 for more information

**Comment by crocket** [comment]
I know why it happens. I was hoping that you removed dotnet from layout.conf because adding more third party overlays complicates package management.
